version: "3.9"
services:
  ctfbot-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_USER: ctfbot
    volumes:
      - ctfbot-db:/var/lib/postgresql/data
    networks:
      - ctfbot-net
      - redash-sources
  ctfbot:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      PGPASSWORD: "${PGPASSWORD}"
      PGHOST: "ctfbot-db"
      NODE_ENV: "production"
    networks:
      - ctfbot-net
networks:
  ctfbot-net:
    driver: bridge
  redash-sources:
    name: redash-sources
volumes:
  ctfbot-db:



